name: Python Script

on:
  schedule:
    - cron: '*/1 * * * *'  # 每分钟运行一次

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 代码
      uses: actions/checkout@v2

    - name: 设置 Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # 选择你想要的 Python 版本

    - name: 生成 requirements.txt
      run: |
        pip freeze > requirements.txt

    - name: 安装 Python 依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 运行 Python 脚本
      run: python main.py
