name: Python Script

on:
  workflow_dispatch:
  schedule:
    - cron: '*/1 * * * *'  # 每分钟运行一次

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 代码
      uses: actions/checkout@v3

    - name: 设置 Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # 选择你想要的 Python 版本

    - name: 运行 Python 脚本
      run: python main.py
